name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-app .
    
    - name: Install dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Push to Docker Registry
      if: success()
      run: |
        echo "DOCKER_PASSWORD=dckr_pat_NVtHRJ4mrRuORM-tjG1AIVVUHSo" | docker login -u "yukihiradeve" --password-stdin
        docker tag my-app my-registry/my-app
        docker push my-registry/my-app
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
