name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Run Unit Tests
      run: docker run my-app /path/to/tests

    - name: Push to Docker Registry
      if: success()  # S'assure que les étapes précédentes ont réussi
      run: |
        echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker tag my-app my-registry/my-app
        docker push my-registry/my-app
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
